spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: NguyenVanSuong@2001
    url: jdbc:mysql://0.0.0.0:3306/football
  jpa:
    show-sql: true
  properties:
    hibernate:
      format_sql: true