INSERT INTO football._DISTRICT (id, name, province_id) VALUES (1, 'Quận Ba Đình', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (2, 'Quận Hoàn Kiếm', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (3, 'Quận Tây Hồ', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (4, 'Quận Long Biên', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (5, 'Quận Cầu Giấy', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (6, 'Quận Đống Đa', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (7, 'Quận Hai Bà Trưng', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (8, 'Quận Hoàng Mai', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (9, 'Quận Thanh Xuân', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (10, 'Huyện Sóc Sơn', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (11, 'Huyện Đông Anh', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (12, 'Huyện Gia Lâm', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (13, 'Quận Nam Từ Liêm', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (14, 'Huyện Thanh Trì', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (15, 'Quận Bắc Từ Liêm', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (16, 'Huyện Mê Linh', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (17, 'Quận Hà Đông', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (18, 'Thị xã Sơn Tây', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (19, 'Huyện Ba Vì', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (20, 'Huyện Phúc Thọ', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (21, 'Huyện Đan Phượng', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (22, 'Huyện Hoài Đức', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (23, 'Huyện Quốc Oai', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (24, 'Huyện Thạch Thất', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (25, 'Huyện Chương Mỹ', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (26, 'Huyện Thanh Oai', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (27, 'Huyện Thường Tín', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (28, 'Huyện Phú Xuyên', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (29, 'Huyện Ứng Hòa', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (30, 'Huyện Mỹ Đức', 1);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (31, 'Thành phố Hà Giang', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (32, 'Huyện Đồng Văn', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (33, 'Huyện Mèo Vạc', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (34, 'Huyện Yên Minh', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (35, 'Huyện Quản Bạ', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (36, 'Huyện Vị Xuyên', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (37, 'Huyện Bắc Mê', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (38, 'Huyện Hoàng Su Phì', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (39, 'Huyện Xín Mần', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (40, 'Huyện Bắc Quang', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (41, 'Huyện Quang Bình', 2);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (42, 'Thành phố Cao Bằng', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (43, 'Huyện Bảo Lâm', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (44, 'Huyện Bảo Lạc', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (45, 'Huyện Hà Quảng', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (46, 'Huyện Trùng Khánh', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (47, 'Huyện Hạ Lang', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (48, 'Huyện Quảng Hòa', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (49, 'Huyện Hoà An', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (50, 'Huyện Nguyên Bình', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (51, 'Huyện Thạch An', 3);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (52, 'Thành Phố Bắc Kạn', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (53, 'Huyện Pác Nặm', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (54, 'Huyện Ba Bể', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (55, 'Huyện Ngân Sơn', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (56, 'Huyện Bạch Thông', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (57, 'Huyện Chợ Đồn', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (58, 'Huyện Chợ Mới', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (59, 'Huyện Na Rì', 4);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (60, 'Thành phố Tuyên Quang', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (61, 'Huyện Lâm Bình', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (62, 'Huyện Na Hang', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (63, 'Huyện Chiêm Hóa', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (64, 'Huyện Hàm Yên', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (65, 'Huyện Yên Sơn', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (66, 'Huyện Sơn Dương', 5);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (67, 'Thành phố Lào Cai', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (68, 'Huyện Bát Xát', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (69, 'Huyện Mường Khương', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (70, 'Huyện Si Ma Cai', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (71, 'Huyện Bắc Hà', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (72, 'Huyện Bảo Thắng', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (73, 'Huyện Bảo Yên', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (74, 'Thị xã Sa Pa', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (75, 'Huyện Văn Bàn', 6);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (76, 'Thành phố Điện Biên Phủ', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (77, 'Thị xã Mường Lay', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (78, 'Huyện Mường Nhé', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (79, 'Huyện Mường Chà', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (80, 'Huyện Tủa Chùa', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (81, 'Huyện Tuần Giáo', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (82, 'Huyện Điện Biên', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (83, 'Huyện Điện Biên Đông', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (84, 'Huyện Mường Ảng', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (85, 'Huyện Nậm Pồ', 7);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (86, 'Thành phố Lai Châu', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (87, 'Huyện Tam Đường', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (88, 'Huyện Mường Tè', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (89, 'Huyện Sìn Hồ', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (90, 'Huyện Phong Thổ', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (91, 'Huyện Than Uyên', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (92, 'Huyện Tân Uyên', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (93, 'Huyện Nậm Nhùn', 8);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (94, 'Thành phố Sơn La', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (95, 'Huyện Quỳnh Nhai', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (96, 'Huyện Thuận Châu', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (97, 'Huyện Mường La', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (98, 'Huyện Bắc Yên', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (99, 'Huyện Phù Yên', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (100, 'Huyện Mộc Châu', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (101, 'Huyện Yên Châu', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (102, 'Huyện Mai Sơn', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (103, 'Huyện Sông Mã', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (104, 'Huyện Sốp Cộp', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (105, 'Huyện Vân Hồ', 9);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (106, 'Thành phố Yên Bái', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (107, 'Thị xã Nghĩa Lộ', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (108, 'Huyện Lục Yên', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (109, 'Huyện Văn Yên', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (110, 'Huyện Mù Căng Chải', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (111, 'Huyện Trấn Yên', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (112, 'Huyện Trạm Tấu', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (113, 'Huyện Văn Chấn', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (114, 'Huyện Yên Bình', 10);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (115, 'Thành phố Hòa Bình', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (116, 'Huyện Đà Bắc', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (117, 'Huyện Lương Sơn', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (118, 'Huyện Kim Bôi', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (119, 'Huyện Cao Phong', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (120, 'Huyện Tân Lạc', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (121, 'Huyện Mai Châu', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (122, 'Huyện Lạc Sơn', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (123, 'Huyện Yên Thủy', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (124, 'Huyện Lạc Thủy', 11);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (125, 'Thành phố Thái Nguyên', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (126, 'Thành phố Sông Công', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (127, 'Huyện Định Hóa', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (128, 'Huyện Phú Lương', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (129, 'Huyện Đồng Hỷ', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (130, 'Huyện Võ Nhai', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (131, 'Huyện Đại Từ', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (132, 'Thị xã Phổ Yên', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (133, 'Huyện Phú Bình', 12);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (134, 'Thành phố Lạng Sơn', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (135, 'Huyện Tràng Định', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (136, 'Huyện Bình Gia', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (137, 'Huyện Văn Lãng', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (138, 'Huyện Cao Lộc', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (139, 'Huyện Văn Quan', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (140, 'Huyện Bắc Sơn', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (141, 'Huyện Hữu Lũng', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (142, 'Huyện Chi Lăng', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (143, 'Huyện Lộc Bình', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (144, 'Huyện Đình Lập', 13);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (145, 'Thành phố Hạ Long', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (146, 'Thành phố Móng Cái', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (147, 'Thành phố Cẩm Phả', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (148, 'Thành phố Uông Bí', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (149, 'Huyện Bình Liêu', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (150, 'Huyện Tiên Yên', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (151, 'Huyện Đầm Hà', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (152, 'Huyện Hải Hà', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (153, 'Huyện Ba Chẽ', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (154, 'Huyện Vân Đồn', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (155, 'Thị xã Đông Triều', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (156, 'Thị xã Quảng Yên', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (157, 'Huyện Cô Tô', 14);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (158, 'Thành phố Bắc Giang', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (159, 'Huyện Yên Thế', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (160, 'Huyện Tân Yên', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (161, 'Huyện Lạng Giang', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (162, 'Huyện Lục Nam', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (163, 'Huyện Lục Ngạn', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (164, 'Huyện Sơn Động', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (165, 'Huyện Yên Dũng', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (166, 'Huyện Việt Yên', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (167, 'Huyện Hiệp Hòa', 15);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (168, 'Thành phố Việt Trì', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (169, 'Thị xã Phú Thọ', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (170, 'Huyện Đoan Hùng', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (171, 'Huyện Hạ Hoà', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (172, 'Huyện Thanh Ba', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (173, 'Huyện Phù Ninh', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (174, 'Huyện Yên Lập', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (175, 'Huyện Cẩm Khê', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (176, 'Huyện Tam Nông', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (177, 'Huyện Lâm Thao', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (178, 'Huyện Thanh Sơn', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (179, 'Huyện Thanh Thuỷ', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (180, 'Huyện Tân Sơn', 16);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (181, 'Thành phố Vĩnh Yên', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (182, 'Thành phố Phúc Yên', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (183, 'Huyện Lập Thạch', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (184, 'Huyện Tam Dương', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (185, 'Huyện Tam Đảo', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (186, 'Huyện Bình Xuyên', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (187, 'Huyện Yên Lạc', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (188, 'Huyện Vĩnh Tường', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (189, 'Huyện Sông Lô', 17);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (190, 'Thành phố Bắc Ninh', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (191, 'Huyện Yên Phong', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (192, 'Huyện Quế Võ', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (193, 'Huyện Tiên Du', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (194, 'Thị xã Từ Sơn', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (195, 'Huyện Thuận Thành', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (196, 'Huyện Gia Bình', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (197, 'Huyện Lương Tài', 18);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (198, 'Thành phố Hải Dương', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (199, 'Thành phố Chí Linh', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (200, 'Huyện Nam Sách', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (201, 'Thị xã Kinh Môn', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (202, 'Huyện Kim Thành', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (203, 'Huyện Thanh Hà', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (204, 'Huyện Cẩm Giàng', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (205, 'Huyện Bình Giang', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (206, 'Huyện Gia Lộc', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (207, 'Huyện Tứ Kỳ', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (208, 'Huyện Ninh Giang', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (209, 'Huyện Thanh Miện', 19);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (210, 'Quận Hồng Bàng', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (211, 'Quận Ngô Quyền', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (212, 'Quận Lê Chân', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (213, 'Quận Hải An', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (214, 'Quận Kiến An', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (215, 'Quận Đồ Sơn', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (216, 'Quận Dương Kinh', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (217, 'Huyện Thuỷ Nguyên', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (218, 'Huyện An Dương', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (219, 'Huyện An Lão', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (220, 'Huyện Kiến Thuỵ', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (221, 'Huyện Tiên Lãng', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (222, 'Huyện Vĩnh Bảo', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (223, 'Huyện Cát Hải', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (224, 'Huyện Bạch Long Vĩ', 20);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (225, 'Thành phố Hưng Yên', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (226, 'Huyện Văn Lâm', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (227, 'Huyện Văn Giang', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (228, 'Huyện Yên Mỹ', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (229, 'Thị xã Mỹ Hào', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (230, 'Huyện Ân Thi', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (231, 'Huyện Khoái Châu', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (232, 'Huyện Kim Động', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (233, 'Huyện Tiên Lữ', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (234, 'Huyện Phù Cừ', 21);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (235, 'Thành phố Thái Bình', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (236, 'Huyện Quỳnh Phụ', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (237, 'Huyện Hưng Hà', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (238, 'Huyện Đông Hưng', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (239, 'Huyện Thái Thụy', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (240, 'Huyện Tiền Hải', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (241, 'Huyện Kiến Xương', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (242, 'Huyện Vũ Thư', 22);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (243, 'Thành phố Phủ Lý', 23);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (244, 'Thị xã Duy Tiên', 23);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (245, 'Huyện Kim Bảng', 23);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (246, 'Huyện Thanh Liêm', 23);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (247, 'Huyện Bình Lục', 23);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (248, 'Huyện Lý Nhân', 23);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (249, 'Thành phố Nam Định', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (250, 'Huyện Mỹ Lộc', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (251, 'Huyện Vụ Bản', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (252, 'Huyện Ý Yên', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (253, 'Huyện Nghĩa Hưng', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (254, 'Huyện Nam Trực', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (255, 'Huyện Trực Ninh', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (256, 'Huyện Xuân Trường', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (257, 'Huyện Giao Thủy', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (258, 'Huyện Hải Hậu', 24);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (259, 'Thành phố Ninh Bình', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (260, 'Thành phố Tam Điệp', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (261, 'Huyện Nho Quan', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (262, 'Huyện Gia Viễn', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (263, 'Huyện Hoa Lư', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (264, 'Huyện Yên Khánh', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (265, 'Huyện Kim Sơn', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (266, 'Huyện Yên Mô', 25);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (267, 'Thành phố Thanh Hóa', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (268, 'Thị xã Bỉm Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (269, 'Thành phố Sầm Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (270, 'Huyện Mường Lát', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (271, 'Huyện Quan Hóa', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (272, 'Huyện Bá Thước', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (273, 'Huyện Quan Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (274, 'Huyện Lang Chánh', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (275, 'Huyện Ngọc Lặc', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (276, 'Huyện Cẩm Thủy', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (277, 'Huyện Thạch Thành', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (278, 'Huyện Hà Trung', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (279, 'Huyện Vĩnh Lộc', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (280, 'Huyện Yên Định', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (281, 'Huyện Thọ Xuân', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (282, 'Huyện Thường Xuân', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (283, 'Huyện Triệu Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (284, 'Huyện Thiệu Hóa', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (285, 'Huyện Hoằng Hóa', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (286, 'Huyện Hậu Lộc', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (287, 'Huyện Nga Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (288, 'Huyện Như Xuân', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (289, 'Huyện Như Thanh', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (290, 'Huyện Nông Cống', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (291, 'Huyện Đông Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (292, 'Huyện Quảng Xương', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (293, 'Thị xã Nghi Sơn', 26);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (294, 'Thành phố Vinh', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (295, 'Thị xã Cửa Lò', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (296, 'Thị xã Thái Hoà', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (297, 'Huyện Quế Phong', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (298, 'Huyện Quỳ Châu', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (299, 'Huyện Kỳ Sơn', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (300, 'Huyện Tương Dương', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (301, 'Huyện Nghĩa Đàn', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (302, 'Huyện Quỳ Hợp', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (303, 'Huyện Quỳnh Lưu', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (304, 'Huyện Con Cuông', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (305, 'Huyện Tân Kỳ', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (306, 'Huyện Anh Sơn', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (307, 'Huyện Diễn Châu', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (308, 'Huyện Yên Thành', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (309, 'Huyện Đô Lương', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (310, 'Huyện Thanh Chương', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (311, 'Huyện Nghi Lộc', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (312, 'Huyện Nam Đàn', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (313, 'Huyện Hưng Nguyên', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (314, 'Thị xã Hoàng Mai', 27);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (315, 'Thành phố Hà Tĩnh', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (316, 'Thị xã Hồng Lĩnh', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (317, 'Huyện Hương Sơn', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (318, 'Huyện Đức Thọ', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (319, 'Huyện Vũ Quang', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (320, 'Huyện Nghi Xuân', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (321, 'Huyện Can Lộc', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (322, 'Huyện Hương Khê', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (323, 'Huyện Thạch Hà', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (324, 'Huyện Cẩm Xuyên', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (325, 'Huyện Kỳ Anh', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (326, 'Huyện Lộc Hà', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (327, 'Thị xã Kỳ Anh', 28);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (328, 'Thành Phố Đồng Hới', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (329, 'Huyện Minh Hóa', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (330, 'Huyện Tuyên Hóa', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (331, 'Huyện Quảng Trạch', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (332, 'Huyện Bố Trạch', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (333, 'Huyện Quảng Ninh', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (334, 'Huyện Lệ Thủy', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (335, 'Thị xã Ba Đồn', 29);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (336, 'Thành phố Đông Hà', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (337, 'Thị xã Quảng Trị', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (338, 'Huyện Vĩnh Linh', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (339, 'Huyện Hướng Hóa', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (340, 'Huyện Gio Linh', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (341, 'Huyện Đa Krông', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (342, 'Huyện Cam Lộ', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (343, 'Huyện Triệu Phong', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (344, 'Huyện Hải Lăng', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (345, 'Huyện Cồn Cỏ', 30);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (346, 'Thành phố Huế', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (347, 'Huyện Phong Điền', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (348, 'Huyện Quảng Điền', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (349, 'Huyện Phú Vang', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (350, 'Thị xã Hương Thủy', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (351, 'Thị xã Hương Trà', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (352, 'Huyện A Lưới', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (353, 'Huyện Phú Lộc', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (354, 'Huyện Nam Đông', 31);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (355, 'Quận Liên Chiểu', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (356, 'Quận Thanh Khê', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (357, 'Quận Hải Châu', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (358, 'Quận Sơn Trà', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (359, 'Quận Ngũ Hành Sơn', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (360, 'Quận Cẩm Lệ', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (361, 'Huyện Hòa Vang', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (362, 'Huyện Hoàng Sa', 32);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (363, 'Thành phố Tam Kỳ', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (364, 'Thành phố Hội An', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (365, 'Huyện Tây Giang', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (366, 'Huyện Đông Giang', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (367, 'Huyện Đại Lộc', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (368, 'Thị xã Điện Bàn', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (369, 'Huyện Duy Xuyên', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (370, 'Huyện Quế Sơn', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (371, 'Huyện Nam Giang', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (372, 'Huyện Phước Sơn', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (373, 'Huyện Hiệp Đức', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (374, 'Huyện Thăng Bình', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (375, 'Huyện Tiên Phước', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (376, 'Huyện Bắc Trà My', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (377, 'Huyện Nam Trà My', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (378, 'Huyện Núi Thành', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (379, 'Huyện Phú Ninh', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (380, 'Huyện Nông Sơn', 33);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (381, 'Thành phố Quảng Ngãi', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (382, 'Huyện Bình Sơn', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (383, 'Huyện Trà Bồng', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (384, 'Huyện Sơn Tịnh', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (385, 'Huyện Tư Nghĩa', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (386, 'Huyện Sơn Hà', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (387, 'Huyện Sơn Tây', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (388, 'Huyện Minh Long', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (389, 'Huyện Nghĩa Hành', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (390, 'Huyện Mộ Đức', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (391, 'Thị xã Đức Phổ', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (392, 'Huyện Ba Tơ', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (393, 'Huyện Lý Sơn', 34);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (394, 'Thành phố Quy Nhơn', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (395, 'Huyện An Lão', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (396, 'Thị xã Hoài Nhơn', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (397, 'Huyện Hoài Ân', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (398, 'Huyện Phù Mỹ', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (399, 'Huyện Vĩnh Thạnh', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (400, 'Huyện Tây Sơn', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (401, 'Huyện Phù Cát', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (402, 'Thị xã An Nhơn', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (403, 'Huyện Tuy Phước', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (404, 'Huyện Vân Canh', 35);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (405, 'Thành phố Tuy Hoà', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (406, 'Thị xã Sông Cầu', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (407, 'Huyện Đồng Xuân', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (408, 'Huyện Tuy An', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (409, 'Huyện Sơn Hòa', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (410, 'Huyện Sông Hinh', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (411, 'Huyện Tây Hoà', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (412, 'Huyện Phú Hoà', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (413, 'Thị xã Đông Hòa', 36);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (414, 'Thành phố Nha Trang', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (415, 'Thành phố Cam Ranh', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (416, 'Huyện Cam Lâm', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (417, 'Huyện Vạn Ninh', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (418, 'Thị xã Ninh Hòa', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (419, 'Huyện Khánh Vĩnh', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (420, 'Huyện Diên Khánh', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (421, 'Huyện Khánh Sơn', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (422, 'Huyện Trường Sa', 37);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (423, 'Thành phố Phan Rang-Tháp Chàm', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (424, 'Huyện Bác Ái', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (425, 'Huyện Ninh Sơn', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (426, 'Huyện Ninh Hải', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (427, 'Huyện Ninh Phước', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (428, 'Huyện Thuận Bắc', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (429, 'Huyện Thuận Nam', 38);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (430, 'Thành phố Phan Thiết', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (431, 'Thị xã La Gi', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (432, 'Huyện Tuy Phong', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (433, 'Huyện Bắc Bình', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (434, 'Huyện Hàm Thuận Bắc', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (435, 'Huyện Hàm Thuận Nam', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (436, 'Huyện Tánh Linh', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (437, 'Huyện Đức Linh', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (438, 'Huyện Hàm Tân', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (439, 'Huyện Phú Quí', 39);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (440, 'Thành phố Kon Tum', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (441, 'Huyện Đắk Glei', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (442, 'Huyện Ngọc Hồi', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (443, 'Huyện Đắk Tô', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (444, 'Huyện Kon Plông', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (445, 'Huyện Kon Rẫy', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (446, 'Huyện Đắk Hà', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (447, 'Huyện Sa Thầy', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (448, 'Huyện Tu Mơ Rông', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (449, 'Huyện Ia H'' Drai', 40);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (450, 'Thành phố Pleiku', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (451, 'Thị xã An Khê', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (452, 'Thị xã Ayun Pa', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (453, 'Huyện KBang', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (454, 'Huyện Đăk Đoa', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (455, 'Huyện Chư Păh', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (456, 'Huyện Ia Grai', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (457, 'Huyện Mang Yang', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (458, 'Huyện Kông Chro', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (459, 'Huyện Đức Cơ', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (460, 'Huyện Chư Prông', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (461, 'Huyện Chư Sê', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (462, 'Huyện Đăk Pơ', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (463, 'Huyện Ia Pa', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (464, 'Huyện Krông Pa', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (465, 'Huyện Phú Thiện', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (466, 'Huyện Chư Pưh', 41);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (467, 'Thành phố Buôn Ma Thuột', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (468, 'Thị xã Buôn Hồ', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (469, 'Huyện Ea H''leo', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (470, 'Huyện Ea Súp', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (471, 'Huyện Buôn Đôn', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (472, 'Huyện Cư M''gar', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (473, 'Huyện Krông Búk', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (474, 'Huyện Krông Năng', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (475, 'Huyện Ea Kar', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (476, 'Huyện M''Đrắk', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (477, 'Huyện Krông Bông', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (478, 'Huyện Krông Pắc', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (479, 'Huyện Krông A Na', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (480, 'Huyện Lắk', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (481, 'Huyện Cư Kuin', 42);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (482, 'Thành phố Gia Nghĩa', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (483, 'Huyện Đăk Glong', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (484, 'Huyện Cư Jút', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (485, 'Huyện Đắk Mil', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (486, 'Huyện Krông Nô', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (487, 'Huyện Đắk Song', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (488, 'Huyện Đắk R''Lấp', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (489, 'Huyện Tuy Đức', 43);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (490, 'Thành phố Đà Lạt', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (491, 'Thành phố Bảo Lộc', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (492, 'Huyện Đam Rông', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (493, 'Huyện Lạc Dương', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (494, 'Huyện Lâm Hà', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (495, 'Huyện Đơn Dương', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (496, 'Huyện Đức Trọng', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (497, 'Huyện Di Linh', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (498, 'Huyện Bảo Lâm', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (499, 'Huyện Đạ Huoai', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (500, 'Huyện Đạ Tẻh', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (501, 'Huyện Cát Tiên', 44);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (502, 'Thị xã Phước Long', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (503, 'Thành phố Đồng Xoài', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (504, 'Thị xã Bình Long', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (505, 'Huyện Bù Gia Mập', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (506, 'Huyện Lộc Ninh', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (507, 'Huyện Bù Đốp', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (508, 'Huyện Hớn Quản', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (509, 'Huyện Đồng Phú', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (510, 'Huyện Bù Đăng', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (511, 'Huyện Chơn Thành', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (512, 'Huyện Phú Riềng', 45);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (513, 'Thành phố Tây Ninh', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (514, 'Huyện Tân Biên', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (515, 'Huyện Tân Châu', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (516, 'Huyện Dương Minh Châu', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (517, 'Huyện Châu Thành', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (518, 'Thị xã Hòa Thành', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (519, 'Huyện Gò Dầu', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (520, 'Huyện Bến Cầu', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (521, 'Thị xã Trảng Bàng', 46);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (522, 'Thành phố Thủ Dầu Một', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (523, 'Huyện Bàu Bàng', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (524, 'Huyện Dầu Tiếng', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (525, 'Thị xã Bến Cát', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (526, 'Huyện Phú Giáo', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (527, 'Thị xã Tân Uyên', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (528, 'Thành phố Dĩ An', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (529, 'Thành phố Thuận An', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (530, 'Huyện Bắc Tân Uyên', 47);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (531, 'Thành phố Biên Hòa', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (532, 'Thành phố Long Khánh', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (533, 'Huyện Tân Phú', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (534, 'Huyện Vĩnh Cửu', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (535, 'Huyện Định Quán', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (536, 'Huyện Trảng Bom', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (537, 'Huyện Thống Nhất', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (538, 'Huyện Cẩm Mỹ', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (539, 'Huyện Long Thành', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (540, 'Huyện Xuân Lộc', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (541, 'Huyện Nhơn Trạch', 48);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (542, 'Thành phố Vũng Tàu', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (543, 'Thành phố Bà Rịa', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (544, 'Huyện Châu Đức', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (545, 'Huyện Xuyên Mộc', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (546, 'Huyện Long Điền', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (547, 'Huyện Đất Đỏ', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (548, 'Thị xã Phú Mỹ', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (549, 'Huyện Côn Đảo', 49);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (550, 'Quận 1', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (551, 'Quận 12', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (552, 'Quận Gò Vấp', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (553, 'Quận Bình Thạnh', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (554, 'Quận Tân Bình', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (555, 'Quận Tân Phú', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (556, 'Quận Phú Nhuận', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (557, 'Thành phố Thủ Đức', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (558, 'Quận 3', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (559, 'Quận 10', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (560, 'Quận 11', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (561, 'Quận 4', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (562, 'Quận 5', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (563, 'Quận 6', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (564, 'Quận 8', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (565, 'Quận Bình Tân', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (566, 'Quận 7', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (567, 'Huyện Củ Chi', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (568, 'Huyện Hóc Môn', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (569, 'Huyện Bình Chánh', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (570, 'Huyện Nhà Bè', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (571, 'Huyện Cần Giờ', 50);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (572, 'Thành phố Tân An', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (573, 'Thị xã Kiến Tường', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (574, 'Huyện Tân Hưng', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (575, 'Huyện Vĩnh Hưng', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (576, 'Huyện Mộc Hóa', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (577, 'Huyện Tân Thạnh', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (578, 'Huyện Thạnh Hóa', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (579, 'Huyện Đức Huệ', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (580, 'Huyện Đức Hòa', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (581, 'Huyện Bến Lức', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (582, 'Huyện Thủ Thừa', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (583, 'Huyện Tân Trụ', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (584, 'Huyện Cần Đước', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (585, 'Huyện Cần Giuộc', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (586, 'Huyện Châu Thành', 51);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (587, 'Thành phố Mỹ Tho', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (588, 'Thị xã Gò Công', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (589, 'Thị xã Cai Lậy', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (590, 'Huyện Tân Phước', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (591, 'Huyện Cái Bè', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (592, 'Huyện Cai Lậy', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (593, 'Huyện Châu Thành', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (594, 'Huyện Chợ Gạo', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (595, 'Huyện Gò Công Tây', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (596, 'Huyện Gò Công Đông', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (597, 'Huyện Tân Phú Đông', 52);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (598, 'Thành phố Bến Tre', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (599, 'Huyện Châu Thành', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (600, 'Huyện Chợ Lách', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (601, 'Huyện Mỏ Cày Nam', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (602, 'Huyện Giồng Trôm', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (603, 'Huyện Bình Đại', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (604, 'Huyện Ba Tri', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (605, 'Huyện Thạnh Phú', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (606, 'Huyện Mỏ Cày Bắc', 53);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (607, 'Thành phố Trà Vinh', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (608, 'Huyện Càng Long', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (609, 'Huyện Cầu Kè', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (610, 'Huyện Tiểu Cần', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (611, 'Huyện Châu Thành', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (612, 'Huyện Cầu Ngang', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (613, 'Huyện Trà Cú', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (614, 'Huyện Duyên Hải', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (615, 'Thị xã Duyên Hải', 54);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (616, 'Thành phố Vĩnh Long', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (617, 'Huyện Long Hồ', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (618, 'Huyện Mang Thít', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (619, 'Huyện Vũng Liêm', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (620, 'Huyện Tam Bình', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (621, 'Thị xã Bình Minh', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (622, 'Huyện Trà Ôn', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (623, 'Huyện Bình Tân', 55);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (624, 'Thành phố Cao Lãnh', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (625, 'Thành phố Sa Đéc', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (626, 'Thành phố Hồng Ngự', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (627, 'Huyện Tân Hồng', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (628, 'Huyện Hồng Ngự', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (629, 'Huyện Tam Nông', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (630, 'Huyện Tháp Mười', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (631, 'Huyện Cao Lãnh', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (632, 'Huyện Thanh Bình', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (633, 'Huyện Lấp Vò', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (634, 'Huyện Lai Vung', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (635, 'Huyện Châu Thành', 56);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (636, 'Thành phố Long Xuyên', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (637, 'Thành phố Châu Đốc', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (638, 'Huyện An Phú', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (639, 'Thị xã Tân Châu', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (640, 'Huyện Phú Tân', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (641, 'Huyện Châu Phú', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (642, 'Huyện Tịnh Biên', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (643, 'Huyện Tri Tôn', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (644, 'Huyện Châu Thành', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (645, 'Huyện Chợ Mới', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (646, 'Huyện Thoại Sơn', 57);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (647, 'Thành phố Rạch Giá', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (648, 'Thành phố Hà Tiên', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (649, 'Huyện Kiên Lương', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (650, 'Huyện Hòn Đất', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (651, 'Huyện Tân Hiệp', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (652, 'Huyện Châu Thành', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (653, 'Huyện Giồng Riềng', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (654, 'Huyện Gò Quao', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (655, 'Huyện An Biên', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (656, 'Huyện An Minh', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (657, 'Huyện Vĩnh Thuận', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (658, 'Thành phố Phú Quốc', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (659, 'Huyện Kiên Hải', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (660, 'Huyện U Minh Thượng', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (661, 'Huyện Giang Thành', 58);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (662, 'Quận Ninh Kiều', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (663, 'Quận Ô Môn', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (664, 'Quận Bình Thuỷ', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (665, 'Quận Cái Răng', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (666, 'Quận Thốt Nốt', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (667, 'Huyện Vĩnh Thạnh', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (668, 'Huyện Cờ Đỏ', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (669, 'Huyện Phong Điền', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (670, 'Huyện Thới Lai', 59);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (671, 'Thành phố Vị Thanh', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (672, 'Thành phố Ngã Bảy', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (673, 'Huyện Châu Thành A', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (674, 'Huyện Châu Thành', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (675, 'Huyện Phụng Hiệp', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (676, 'Huyện Vị Thuỷ', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (677, 'Huyện Long Mỹ', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (678, 'Thị xã Long Mỹ', 60);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (679, 'Thành phố Sóc Trăng', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (680, 'Huyện Châu Thành', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (681, 'Huyện Kế Sách', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (682, 'Huyện Mỹ Tú', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (683, 'Huyện Cù Lao Dung', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (684, 'Huyện Long Phú', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (685, 'Huyện Mỹ Xuyên', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (686, 'Thị xã Ngã Năm', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (687, 'Huyện Thạnh Trị', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (688, 'Thị xã Vĩnh Châu', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (689, 'Huyện Trần Đề', 61);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (690, 'Thành phố Bạc Liêu', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (691, 'Huyện Hồng Dân', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (692, 'Huyện Phước Long', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (693, 'Huyện Vĩnh Lợi', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (694, 'Thị xã Giá Rai', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (695, 'Huyện Đông Hải', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (696, 'Huyện Hoà Bình', 62);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (697, 'Thành phố Cà Mau', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (698, 'Huyện U Minh', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (699, 'Huyện Thới Bình', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (700, 'Huyện Trần Văn Thời', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (701, 'Huyện Cái Nước', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (702, 'Huyện Đầm Dơi', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (703, 'Huyện Năm Căn', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (704, 'Huyện Phú Tân', 63);
INSERT INTO football._DISTRICT (id, name, province_id) VALUES (705, 'Huyện Ngọc Hiển', 63);
