INSERT INTO football._PROVINCE (id, name) VALUES (1, 'Thành phố Hà Nội');
INSERT INTO football._PROVINCE (id, name) VALUES (2, 'Tỉnh Hà Giang');
INSERT INTO football._PROVINCE (id, name) VALUES (3, 'Tỉnh Cao Bằng');
INSERT INTO football._PROVINCE (id, name) VALUES (4, 'Tỉnh Bắc Kạn');
INSERT INTO football._PROVINCE (id, name) VALUES (5, 'Tỉnh Tuyên Quang');
INSERT INTO football._PROVINCE (id, name) VALUES (6, 'Tỉnh Lào Cai');
INSERT INTO football._PROVINCE (id, name) VALUES (7, 'Tỉnh Điện Biên');
INSERT INTO football._PROVINCE (id, name) VALUES (8, 'Tỉnh Lai Châu');
INSERT INTO football._PROVINCE (id, name) VALUES (9, 'Tỉnh Sơn La');
INSERT INTO football._PROVINCE (id, name) VALUES (10, 'Tỉnh Yên Bái');
INSERT INTO football._PROVINCE (id, name) VALUES (11, 'Tỉnh Hoà Bình');
INSERT INTO football._PROVINCE (id, name) VALUES (12, 'Tỉnh Thái Nguyên');
INSERT INTO football._PROVINCE (id, name) VALUES (13, 'Tỉnh Lạng Sơn');
INSERT INTO football._PROVINCE (id, name) VALUES (14, 'Tỉnh Quảng Ninh');
INSERT INTO football._PROVINCE (id, name) VALUES (15, 'Tỉnh Bắc Giang');
INSERT INTO football._PROVINCE (id, name) VALUES (16, 'Tỉnh Phú Thọ');
INSERT INTO football._PROVINCE (id, name) VALUES (17, 'Tỉnh Vĩnh Phúc');
INSERT INTO football._PROVINCE (id, name) VALUES (18, 'Tỉnh Bắc Ninh');
INSERT INTO football._PROVINCE (id, name) VALUES (19, 'Tỉnh Hải Dương');
INSERT INTO football._PROVINCE (id, name) VALUES (20, 'Thành phố Hải Phòng');
INSERT INTO football._PROVINCE (id, name) VALUES (21, 'Tỉnh Hưng Yên');
INSERT INTO football._PROVINCE (id, name) VALUES (22, 'Tỉnh Thái Bình');
INSERT INTO football._PROVINCE (id, name) VALUES (23, 'Tỉnh Hà Nam');
INSERT INTO football._PROVINCE (id, name) VALUES (24, 'Tỉnh Nam Định');
INSERT INTO football._PROVINCE (id, name) VALUES (25, 'Tỉnh Ninh Bình');
INSERT INTO football._PROVINCE (id, name) VALUES (26, 'Tỉnh Thanh Hóa');
INSERT INTO football._PROVINCE (id, name) VALUES (27, 'Tỉnh Nghệ An');
INSERT INTO football._PROVINCE (id, name) VALUES (28, 'Tỉnh Hà Tĩnh');
INSERT INTO football._PROVINCE (id, name) VALUES (29, 'Tỉnh Quảng Bình');
INSERT INTO football._PROVINCE (id, name) VALUES (30, 'Tỉnh Quảng Trị');
INSERT INTO football._PROVINCE (id, name) VALUES (31, 'Tỉnh Thừa Thiên Huế');
INSERT INTO football._PROVINCE (id, name) VALUES (32, 'Thành phố Đà Nẵng');
INSERT INTO football._PROVINCE (id, name) VALUES (33, 'Tỉnh Quảng Nam');
INSERT INTO football._PROVINCE (id, name) VALUES (34, 'Tỉnh Quảng Ngãi');
INSERT INTO football._PROVINCE (id, name) VALUES (35, 'Tỉnh Bình Định');
INSERT INTO football._PROVINCE (id, name) VALUES (36, 'Tỉnh Phú Yên');
INSERT INTO football._PROVINCE (id, name) VALUES (37, 'Tỉnh Khánh Hòa');
INSERT INTO football._PROVINCE (id, name) VALUES (38, 'Tỉnh Ninh Thuận');
INSERT INTO football._PROVINCE (id, name) VALUES (39, 'Tỉnh Bình Thuận');
INSERT INTO football._PROVINCE (id, name) VALUES (40, 'Tỉnh Kon Tum');
INSERT INTO football._PROVINCE (id, name) VALUES (41, 'Tỉnh Gia Lai');
INSERT INTO football._PROVINCE (id, name) VALUES (42, 'Tỉnh Đắk Lắk');
INSERT INTO football._PROVINCE (id, name) VALUES (43, 'Tỉnh Đắk Nông');
INSERT INTO football._PROVINCE (id, name) VALUES (44, 'Tỉnh Lâm Đồng');
INSERT INTO football._PROVINCE (id, name) VALUES (45, 'Tỉnh Bình Phước');
INSERT INTO football._PROVINCE (id, name) VALUES (46, 'Tỉnh Tây Ninh');
INSERT INTO football._PROVINCE (id, name) VALUES (47, 'Tỉnh Bình Dương');
INSERT INTO football._PROVINCE (id, name) VALUES (48, 'Tỉnh Đồng Nai');
INSERT INTO football._PROVINCE (id, name) VALUES (49, 'Tỉnh Bà Rịa - Vũng Tàu');
INSERT INTO football._PROVINCE (id, name) VALUES (50, 'Thành phố Hồ Chí Minh');
INSERT INTO football._PROVINCE (id, name) VALUES (51, 'Tỉnh Long An');
INSERT INTO football._PROVINCE (id, name) VALUES (52, 'Tỉnh Tiền Giang');
INSERT INTO football._PROVINCE (id, name) VALUES (53, 'Tỉnh Bến Tre');
INSERT INTO football._PROVINCE (id, name) VALUES (54, 'Tỉnh Trà Vinh');
INSERT INTO football._PROVINCE (id, name) VALUES (55, 'Tỉnh Vĩnh Long');
INSERT INTO football._PROVINCE (id, name) VALUES (56, 'Tỉnh Đồng Tháp');
INSERT INTO football._PROVINCE (id, name) VALUES (57, 'Tỉnh An Giang');
INSERT INTO football._PROVINCE (id, name) VALUES (58, 'Tỉnh Kiên Giang');
INSERT INTO football._PROVINCE (id, name) VALUES (59, 'Thành phố Cần Thơ');
INSERT INTO football._PROVINCE (id, name) VALUES (60, 'Tỉnh Hậu Giang');
INSERT INTO football._PROVINCE (id, name) VALUES (61, 'Tỉnh Sóc Trăng');
INSERT INTO football._PROVINCE (id, name) VALUES (62, 'Tỉnh Bạc Liêu');
INSERT INTO football._PROVINCE (id, name) VALUES (63, 'Tỉnh Cà Mau');
